### ISSUE TITLE
Install plugin

### ISSUE THREAD

**Issue by aleksey-ilin** [simonsmith/cypress-image-snapshot#1]
Hi, @simonsmith.
Command yarn add --dev @simonsmith/cypress-image-snapshot from readme install 6.1.1 version. How to install 7 version?
![image](https://github.com/simonsmith/cypress-image-snapshot/assets/32348899/c7904766-66ca-48d2-8cb3-1f990c8a9e9b)

**Comment by simonsmith** [comment]
@aleksey-ilin Hey, I've not released the new version just yet. Few more tasks to do on the repository and then I will

**Comment by aleksey-ilin** [comment]
Hi, @simonsmith. When do you release a new version?

**Comment by simonsmith** [comment]
I am expecting this week

**Comment by simonsmith** [comment]
https://github.com/simonsmith/cypress-image-snapshot/releases/tag/7.0.0
