### ISSUE TITLE
The requireSnapshots fails only the first time (retries runMode >= 1)

### ISSUE THREAD

**Issue by krzysztof-kobrenczuk-viacomcbs** [simonsmith/cypress-image-snapshot#10]
Hello,

I'm trying to use the --env requireSnapshots=true parameter. However, if I have the Cypress options set to retries runMode:2, then only the first run fails, and subsequent attempts create the snapshots.

`pnpm cypress run --browser electron --spec "cypress/tests/visual/recordView.visual.cy.ts" --env requireSnapshots=true`

![image](https://github.com/simonsmith/cypress-image-snapshot/assets/98817223/e2a897b9-2cc3-4d1a-af42-1a12f4f30a55)

![image](https://github.com/simonsmith/cypress-image-snapshot/assets/98817223/3468e850-5bc7-4a49-a526-95a86be2e488)

Cypress config:
retries: {
        runMode: 2,
    },

**Comment by simonsmith** [comment]
Do you know if this is specific to `2` retries? Wondering if it's just anything more than the first run

**Comment by krzysztof-kobrenczuk-viacomcbs** [comment]
The same behavior is also for 1 retry, seems that this functionality works only for the first run
![image](https://github.com/simonsmith/cypress-image-snapshot/assets/98817223/9344beda-fb85-4381-9a6a-18b915554b52)

**Comment by simonsmith** [comment]
Will be fixed in #13

**Comment by simonsmith** [comment]
Released in `8.0.0` - https://github.com/simonsmith/cypress-image-snapshot/releases/tag/8.0.0
