### ISSUE TITLE
How to include snapshots in the report

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [simonsmith/cypress-image-snapshot#11]
[Here](https://github.com/jaredpalmer/cypress-image-snapshot) I've read that:

Run Cypress with --reporter cypress-image-snapshot/reporter in order to report snapshot diffs in your test results. This can be helpful to use with --env failOnSnapshotDiff=false in order to quickly view all failing snapshots and their diffs.

But with thins plugin how can I include snapshots in the report?
It would be fantastic if I could use the `mochawesome` reporter.

I've tried this `mochawesome` config:

```{
    "charts": true,
    "reportPageTitle": "Tests Cypress de Vision",
    "embeddedScreenshots": true,
    "inlineAssets": true
  }```

**Comment by DavidPerezIngeniero** [comment]
This gives me the clue:

https://stackoverflow.com/questions/68347032/screenshots-and-videos-on-cypress-reports

By adding this:
```
import 'cypress-mochawesome-reporter/register';
```
to `e2e.ts`, then magically I can see screenshots and video.
Certainly, this should be shown in the doc.

Snapshots are tried to be shown, but there must be some misconfiguration.

Here is the URL of a snapshot that appears on the report:
```file:///home/david/p/rds/e2e/cypress/reports/html/screenshots/home/david/p/rds/e2e/cypress/snapshots/T001_ABM_puntoMapa.cy.ts/password.snap.png```

Here is the rigth value:
```file:///home/david/p/rds/e2e/cypress/snapshots/T001_ABM_puntoMapa.cy.ts/password.snap.png```

I don't know how to correct this.

![image](https://github.com/simonsmith/cypress-image-snapshot/assets/6008104/3d04c8e5-aa58-44cc-bfb0-64b0a69248b0)

**Comment by simonsmith** [comment]
So at the moment the `reporter` is not officially supported in this fork, as seen in the changelog notes: https://github.com/simonsmith/cypress-image-snapshot/releases/tag/7.0.0

That was the one listed in the original README as `cypress-image-snapshot/reporter`.

In terms of your issue, it might be related to #8 which I'm still working on. There are annoyances with how Cypress writes images to filesystem since version 10. Perhaps we can look at this again once that PR is finished & merged

**Comment by DavidPerezIngeniero** [comment]
Thanks for your answer.

**Comment by simonsmith** [comment]
You should be able to try again with `8.0.1` now, see if that helps. Note this README addition - https://github.com/simonsmith/cypress-image-snapshot#snapshot-paths

**Comment by simonsmith** [comment]
Closing as inactive
