### ISSUE TITLE
[SECURITY] Snapshot names not sanitized

### ISSUE THREAD

**Issue by thib3113** [simonsmith/cypress-image-snapshot#15]
It seems that snapshot names are not sanitized . 

I test something like : 
```
it('test / test name', () => {
  cy.matchImageSnapshot()
})
```

and so it create a folder `test `, and a file ` test name` . 

Can you please sanitize file names ? It seems ([here](https://github.com/cypress-io/cypress/discussions/16005)) that cypress [use the library](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/screenshots.js#L9) [sanitize-filename](https://www.npmjs.com/package/sanitize-filename) . ( or better, use a hash as filename, so less names collision risk . And your are sure there is no strange chars )

also, I'm pretty sure it can destroy a system ... what happen if I name my test with path traversal ? something like : `../../../etc/password` . 

---

I tested it . And we can write any files on a developper computer .

( not exactly with the same name I say before ... but I'll not tell it here ... in private if you want )
 
Please fix this, and create a [repository-security-advisory](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/publishing-a-repository-security-advisory) to tell people to update to a safe version

**Comment by simonsmith** [comment]
Thanks for highlighting this one @thib3113, should be fixed now 👌🏻

**Comment by thib3113** [comment]
great ! thank you !
