### ISSUE TITLE
When I have option retries in cypress config files with "attempt" in file name will be generated

### ISSUE THREAD

**Issue by ISp1rit** [simonsmith/cypress-image-snapshot#19]
I've added in cypress.config.ts
```
retries: {
  runMode: 2,
},
```

And now when tests are running, if the first attempt failed, then will be generated a new snapshot with a name like:
web-client-app/cypress/snapshots/upload-financial-statements-page/provider/provider_statements_page.cy.ts/page-loaded-laptop-1280x720 (attempt 2).snap.png  

This file tries to find a diff with a file with the same name, but a file with this name not exists, that's why no error will be thrown and a new snapshot with "attempt 2" in the name will be added.

There is a PR in the original repo https://github.com/jaredpalmer/cypress-image-snapshot/pull/155 that I believe fixes this issue, can you check it please?)

**Comment by simonsmith** [comment]
Good spot, looks like a regression I created here - https://github.com/simonsmith/cypress-image-snapshot/commit/ef49519795daf5183f4fac6f3136e194f20f39f4

I'll get a fix out
