### ISSUE TITLE
Missing TypeScript declaration files

### ISSUE THREAD

**Issue by DCzajkowski** [simonsmith/cypress-image-snapshot#2]
When pulling @simonsmith/cypress-image-snapshot@6.1.1 from NPM, the package does not include TS declaration files.

You can preview the package contents here: https://www.npmjs.com/package/@simonsmith/cypress-image-snapshot?activeTab=code

**Comment by simonsmith** [comment]
Yep, I am yet to release version 7 which will include them. I have a couple more tasks to do on the repo and then it will be released

See #1
