### ISSUE TITLE
Error: When failOnSnapshotDiff is set to true, it does not throw any error and it console it

### ISSUE THREAD

**Issue by MaximilianoAdaro** [simonsmith/cypress-image-snapshot#22]
- If I set `failOnSnapshotDiff = true` and the test should fail (it doesn't do it)
- If I do not set failOnSnapshotDiff, so `failOnSnapshotDiff === undefined` it throws the error

The issue is [here](https://github.com/simonsmith/cypress-image-snapshot/blob/c07da6704ee86eaee1270eccaee900dcd28086dc/src/command.ts#L51C11-L51C31)

**Comment by simonsmith** [comment]
Fixed in #29
