### ISSUE TITLE
Errors after upgrading Cypress to 13

### ISSUE THREAD

**Issue by ssurowka** [simonsmith/cypress-image-snapshot#26]
After upgrading Cypress to 13, I ran some visual tests, but there were errors:
<img width="374" alt="image" src="https://github.com/simonsmith/cypress-image-snapshot/assets/119666266/7a715198-b46f-4428-8abf-b865ec5b656b">

**Comment by simonsmith** [comment]
Which version of 13 did you try?

Did the same test work fine on Cypress 12?

**Comment by ssurowka** [comment]
I checked it one more time. It works fine with Cypress 13.2.0. The error above occurred with another plugin update.

**Comment by simonsmith** [comment]
Good to know 👌🏻
