### ISSUE TITLE
Different size images: sometimes it's the correct size, sometimes it's twice the size

### ISSUE THREAD

**Issue by TheColorRed** [simonsmith/cypress-image-snapshot#31]
I am not sure if the issue is with cypress or the snapshot tool, but I am trying to do snapshots of an element, and I am getting two different sizes when the image is created/compared. Sometimes the the snapshot is 16x16 (correct) and other times it is 32x32 (incorrect). I am not sure where this issue is coming from.

Here are the settings:

```ts
// e2e.js

addMatchImageSnapshotCommand({
  failureThreshold: 0.015, // threshold for entire image
  failureThresholdType: 'percent', // percent of image or number of pixels
  customDiffConfig: { threshold: 0.15 }, // threshold for each pixel
  customDiffDir: '../../dist/cypress/visual_diffs',
  customSnapshotsDir: 'src/integration/snapshots', // relative to each lib, such as /netra/apps/card-e2e/*
  e2eSpecDir: 'src/integration',
  scale: false,
  allowSizeMismatch: true, // avoids false positives when running in jenkins
});
```

Here is the test (we use cucumber):

```ts
Then(`Alias {string} matches snapshot {string}`, (alias, imageName) => {
  if (Cypress.browser.isHeadless) {
    cy.get(`@${alias}`).matchImageSnapshot(imageName);
  }
});
```

It seems to go into "snapshot mode" run the command, exit "snapshot mode" and then scales up and then takes the actual snapshot that gets saved to disk.

**Comment by simonsmith** [comment]
Do you get the same problem if you leave all the options as default?

**Comment by TheColorRed** [comment]
I wonder if this issue is because I am using a MacBook, others seem to be having the same issues...

https://github.com/cypress-io/cypress/issues/6485

**Comment by TheColorRed** [comment]
So, using the default settings has no effect on the size issue:

![image](https://github.com/simonsmith/cypress-image-snapshot/assets/1571806/7050deda-5385-4e75-86b3-cbb8bfc19219)

This is on Github actions:

![image](https://github.com/simonsmith/cypress-image-snapshot/assets/1571806/8d9614f1-239c-4ff3-bef9-d01685ce8a4e)

This is my Local:

![image](https://github.com/simonsmith/cypress-image-snapshot/assets/1571806/2927f684-bd85-48ff-8198-6cc868651d00)

**Comment by simonsmith** [comment]
Okay, thanks

Are you creating the image in headless mode as well?

**Comment by simonsmith** [comment]
> I wonder if this issue is because I am using a MacBook, others seem to be having the same issues...

Yes, it might well be. I would always advise creating images in the same mode that your tests run. So generate images in `headless` and then run the tests in that mode as well

In open mode it will use your display DPI

**Comment by simonsmith** [comment]
Alternatively you can generate them inside a Docker container, which will help with consistency on CI machines. I use this approach

**Comment by TheColorRed** [comment]
We always generate in headless, but it still uses the MacBook Retina screen to generate the images. I tested this comment:

> I don't know why but I am also getting double resolution images when running HEADLESS on a mac. I have to actively set my primary monitor to something that is NOT the built in retina screen to get "normal" sized screenshots.

Doing that fixes the issue, however, it's not something that we (the team) should have to be doing to fix it.

I think I will raise an issue to our team and see what approach we want to take. Thanks!

**Comment by simonsmith** [comment]
Okay cool. There are many examples of the Docker + Cypress thing but this repo has a basic setup you can use as a guide as well. Mostly around allowing Docker to see your cypress dir on the host machine so it can write the snapshots back to the repo.

Will close for now 👌🏻
