### ISSUE TITLE
Broken path in open mode

### ISSUE THREAD

**Issue by StMelik** [simonsmith/cypress-image-snapshot#32]
Hi! When using the plugin, I found one bug.

![image](https://github.com/simonsmith/cypress-image-snapshot/assets/93302874/2b1f84e7-5f1c-4b57-abce-996d7a5a94a3)
File - `plugin.ts` on line 76.

If I use an open mod and there is a folder with a dot in the project path (Project.Test), then normalization of the empty string equal dot ('.').

As a result, the path breaks and the tests do not pass.

**Comment by simonsmith** [comment]
Hey,

Is this only in open mode, or did you see it run mode as well?

**Comment by StMelik** [comment]
Yes, it's only in open mode.

I looked at the logs:
run mode - `specName` has the value
open mode - `specName` is empty

**Comment by simonsmith** [comment]
Okay thanks, I have seen differences in how these values are provided from Cypress depending on the mode. Will investigate

**Comment by simonsmith** [comment]
I'm struggling to reproduce this, for example:

<div><img width="299" alt="image" src="https://github.com/simonsmith/cypress-image-snapshot/assets/360703/0cf5ba00-47ef-4a02-9b49-a9d8a946cb47"></div>

<div style="margin-top: 20px"><img width="403" alt="image" src="https://github.com/simonsmith/cypress-image-snapshot/assets/360703/cc644c11-74d1-4532-9265-4dfdc94e457d"></div>

<div style="margin-top: 20px"><img width="287" alt="image" src="https://github.com/simonsmith/cypress-image-snapshot/assets/360703/5a6ea307-25c0-4bbb-a4ae-f5fddf3ef34c"></div>


Directory and file name with dots seems to work fine in open mode. Could you give more detailed reproduction steps?

**Comment by StMelik** [comment]
I created a repository with a test project and described in detail all the steps to reproduce the bug.
https://github.com/StMelik/cypress-image-snapshot-path-bug

**Comment by simonsmith** [comment]
Thanks for the example repo, but I'm not seeing an issue there:

![image](https://github.com/simonsmith/cypress-image-snapshot/assets/360703/8cb8b55d-a60b-485a-a703-8018747c720c)

![image](https://github.com/simonsmith/cypress-image-snapshot/assets/360703/05b3d498-8245-473d-8a37-00fb7e4b1955)

What exact issue are you seeing and what platform are you on? I'm testing this on Mac

**Comment by StMelik** [comment]
I see such a problem.

![image](https://github.com/simonsmith/cypress-image-snapshot/assets/93302874/b4cbe442-8649-40ec-8040-6dcab9dcb5d5)

My platform is windows 10.

**Comment by StMelik** [comment]
Path - D:\my-projects\Test\Test.Project\cypress\snapshots\spec.cy.js (1)
and path - D:\my-projects\Test\TestProject\cypress\screenshots (2)
was joined because in File - `plugin.ts` on line 76 in open mode `screenshotConfig.specName` is equal to an empty string (`"`).

Next, `path.normalize` replaces the empty string with a dot ('.').

As a result, in path (2 - screenshot Config.path) the folder Test.Project becomes TestProject

**Comment by simonsmith** [comment]
Do you see the same issue if you just use `cy.screenshot()`?

**Comment by StMelik** [comment]
If I run `cy.screenshot()` after running Cypress, then there are no errors.

But if I execute `cy.matchImageSnapshot()` at least once, then when calling `cy.screenshot()`, an error appears.

**Comment by simonsmith** [comment]
Fixed in #55
