### ISSUE TITLE
allow removal of .snap in snapshot name

### ISSUE THREAD

**Issue by maximegheraille** [simonsmith/cypress-image-snapshot#33]
Hi,

every snapshot currently has '.snap' appended to the generated filename.

would be nice to have an option to disable that, I did not find a way to get that removed.

here is my current options 
```
const options: CypressImageSnapshotOptions = {
			failureThreshold: 0,
			allowSizeMismatch: true,
			failureThresholdType: 'percent',
			capture: 'viewport',
			comparisonMethod: 'ssim',
			customSnapshotsDir: './cypress/reports/snapshots/${Cypress.spec.fileName}',
			e2eSpecDir: '${Cypress.spec.relative}',
			
		};
```

**Comment by simonsmith** [comment]
Hey,

Yes, it's not an option currently as seen here - https://github.com/simonsmith/cypress-image-snapshot/blob/master/src/plugin.ts#L35

What would be the reason for this, out of curiosity?

**Comment by maximegheraille** [comment]
it is a bit annoying as I am using `mochawesome/addContext.js` for reports and I use my path to get the image but now i have to add '.snap' to the check. I also do not really like a snapshot with this type of name test.snap.png.

Is there a purpose of adding that string for anyone otherwise it is just added for nothing ?

**Comment by simonsmith** [comment]
Yeah, it's just there to make the file name distinct and it can be useful for file searching. Happy to make it a configurable option though
