### ISSUE TITLE
cypress-image-snapshot 9.0.0 is missing the "util" folder on npm

### ISSUE THREAD

**Issue by froissant** [simonsmith/cypress-image-snapshot#35]
Hi!

I've update to version **9.0.0** but I have an error running cypress tests:
```
Error: Webpack Compilation Error
Module not found: Error: Can't resolve './util/extend' 
```

This seems related to the fix for #12

Looking at the [package tarball](https://registry.npmjs.org/@simonsmith/cypress-image-snapshot/-/cypress-image-snapshot-9.0.0.tgz) on npm, I noticed that the **util** folder wasn't included in the archive.
By copying the missing folder manually to ``node_modules``, I was able to run my tests.

I've ran ``yarn build`` and ``yarn ci:build`` on this repo, and both commands correctly output the code with the "util" folder.
The culprit seems to be semantic-release, but I unfortunately cannot debug it 😥

Let me know if you can reproduce the issue or if you need anything else!

**Comment by simonsmith** [comment]
Ah okay, that's odd. I'll take a look now

**Comment by simonsmith** [comment]
I neglected to update the `files` array in `package.json`, my apologies! 

`9.0.1` should be all good now

![image](https://github.com/simonsmith/cypress-image-snapshot/assets/360703/e25bb297-e0d8-4560-bca4-081f5225b381)

**Comment by froissant** [comment]
Many thanks @simonsmith, everything's working fine now 😊
