### ISSUE TITLE
different sizes between open and run mode

### ISSUE THREAD

**Issue by maximegheraille** [simonsmith/cypress-image-snapshot#36]
Hi,

I have a really weird issue, where all my snapshots do match expect for my biggest size (1920x1080).

All my screenshots are created in headless mode but when run in open mode (chrome) it gives this size issue
`Image size (3840x499) different than saved snapshot size (3360x499).`

my Cypress config contains `viewportHeight: 1080, viewportWidth: 1920,` and I do set my viewport before taking/comparing the snapshot `cy.viewport(1920, 1080);`

my options config 
```
const options: CypressImageSnapshotOptions = {
			failureThreshold: 0.1,
			allowSizeMismatch: true,
			failureThresholdType: 'percent',
			capture: 'viewport',
			comparisonMethod: 'ssim',
			customSnapshotsDir: `somepath`,
			e2eSpecDir: `${Cypress.spec.relative}`,
		};
```

**Comment by simonsmith** [comment]
Seems like an issue with Cypress itself, not this plugin - https://github.com/cypress-io/cypress/issues/3324
