### ISSUE TITLE
CypressError: cy.screenshot() failed because it requires a DOM element

### ISSUE THREAD

**Issue by Nek0-hinata** [simonsmith/cypress-image-snapshot#42]
Hi,
When i migrating [cypress-image-snapshot](https://www.npmjs.com/package/cypress-image-snapshot) to your package (also migrate cypress version 9.0 to 10.0), i find some strange error as the image shown after.
<img width="394" alt="image" src="https://github.com/simonsmith/cypress-image-snapshot/assets/81868415/15699f17-5008-47f1-be05-e0d519976947">

 It happened on all my cyress test which used cy.matchImageSnapshot() command and the stack trace point out it happend because of `elementToScreenshot` at file `src/command.ts 70:5`.

I'm confuesed about [this line](https://github.com/simonsmith/cypress-image-snapshot/blob/d1d54621d6991e29c5bf44bac5c6b3b6eae21933/src/command.ts#L63C49-L63C49). When the `prevSubjet` is optional, the `subject` could be null. On this condition, how to use cy.wrap() to do a screenshot.

I dont know what to do next. Am I made some mistake while migration?

**Comment by Nek0-hinata** [comment]
For example, this is how I used in my repo
<img width="769" alt="image" src="https://github.com/simonsmith/cypress-image-snapshot/assets/81868415/cc1585e5-3ca0-4304-b6a6-8514a60913fa">

**Comment by simonsmith** [comment]
This does seem related to #40 as well. It might be necessary to add some tests for this kind of usage and see if they fail. Contributions are welcome otherwise I will do some investigation when I get some time

**Comment by simonsmith** [comment]
I've struggled to reproduce this. As you can see in the tests the plugin works fine with and without a subject (so either `cy.matchImageSnapshot()` or `cy.get('something').matchImageSnapshot()`

https://github.com/simonsmith/cypress-image-snapshot/blob/master/cypress/e2e/matchImageSnapshot.cy.ts#L6-L14

This behaviour is part of Cypress described here - https://docs.cypress.io/api/cypress-api/custom-commands#Optional-with-Types

In the case of this plugin I allow everything:

```ts
  Cypress.Commands.add(
    'matchImageSnapshot',
    {
      prevSubject: ['optional', 'element', 'document', 'window'],
    },
    matchImageSnapshot(defaultOptionsOverrides),
  )
```

If you can provide a concrete way for me to reproduce this (even if it's a fork of the tests in this repo) I'll reopen and investigate
