### ISSUE TITLE
Error when using with `@badeball/cypress-cucumber-preprocessor` 

### ISSUE THREAD

**Issue by AonghusOh** [simonsmith/cypress-image-snapshot#50]
Hi, many thanks for the plugin - it's very promising for my use case and I've been able to get it up and running with a basic project. 

However, I want to use [@badeball/cypress-cucumber-preprocessor ](https://github.com/badeball/cypress-cucumber-preprocessor) so that I can use Given/When/Then syntax in .feature files, but when that's configured, it seems to not capture the snapshots for the image comparison and gives an error: ` Error: Image was NaN% different from saved snapshot with undefined different pixels.
See diff for details: undefined`. Nothing gets written to the `snapshots` directory. The issue is the same with `npx cypress run` and `npx cypress open` and using `--env updateSnapshots=true`

The page is getting loaded etc., as the cypress screenshots capture: 
![Page Display -- Customer visits the page (failed)](https://github.com/simonsmith/cypress-image-snapshot/assets/2061308/80b46982-9e14-4665-85fc-4f59de6d8a4c)

I did get the snapshot comparison working fine without the cucumber configuration. 

Below is the output and configuration of the simple test suite. Any suggestions would be much appreciated! 

**output**
```
cypress-visual-test> npx cypress run --env updateSnapshots=true


DevTools listening on ws://127.0.0.1:51310/devtools/browser/7429ab94-aef7-41d2-9b27-6843f1e8c5ae

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        13.7.1                                                                         │
  │ Browser:        Electron 118 (headless)                                                        │
  │ Node Version:   v18.16.1 (C:\Program Files\nodejs\node.exe)                                    │
  │ Specs:          1 found (page_display.feature)                                                 │
  │ Searched:       **/*.feature                                                                   │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  page_display.feature                                                            (1 of 1)


  Page Display
    1) Customer visits the page


  0 passing (4s)
  1 failing

  1) Page Display
       Customer visits the page:
     Error: Image was NaN% different from saved snapshot with undefined different pixels.
See diff for details: undefined
      at Context.eval (https://example.com/__cypress/tests?p=cypress\support\e2e.js:148:21)
```

**cypress.config.js** - based on the example here: https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/examples/esbuild-cjs/cypress.config.js
```
const { defineConfig } = require('cypress');
const { addMatchImageSnapshotPlugin } = require('@simonsmith/cypress-image-snapshot/plugin');
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const {
  addCucumberPreprocessorPlugin,
} = require("@badeball/cypress-cucumber-preprocessor");
const {
  createEsbuildPlugin,
} = require("@badeball/cypress-cucumber-preprocessor/esbuild");

async function setupNodeEvents(on, config) {
  addMatchImageSnapshotPlugin(on);

  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await addCucumberPreprocessorPlugin(on, config);

  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin(config)],
    })
  );

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}

module.exports = defineConfig({
  e2e: {
    baseUrl: "https://example.com",
    specPattern: "**/*.feature",
    setupNodeEvents,
  },
});
```

**cypress/support/e2e.js**
```
import { addMatchImageSnapshotCommand } from '@simonsmith/cypress-image-snapshot/command';

addMatchImageSnapshotCommand();
```

**package.json**
```
{
  "name": "cypress-visual-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^20.0.3",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.2.0",
    "@simonsmith/cypress-image-snapshot": "^9.0.1",
    "cypress": "^13.7.1"
  }
}
```

**cypress/e2e/page_display.feature**
```
Feature: Page Display
  Scenario: Customer visits the page
    Given a customer
    When they visit the page
    Then the page will be displayed correctly
```

**cypress/e2e/page_display.js**
```
import { Given, When, Then } from "@badeball/cypress-cucumber-preprocessor";

Given('a customer', () => {
  // This step can be used for setup or left empty if there's nothing to define.
});

When('they visit the page', () => {
  cy.visit('https://example.com');
});

Then('the page will be displayed correctly', () => {
  cy.matchImageSnapshot();
});
```

**Comment by simonsmith** [comment]
Hey,

It looks like that perhaps that plugin changes the results from `snapshotResult` here:

https://github.com/simonsmith/cypress-image-snapshot/blob/master/src/command.ts#L73-L103

Just based on the way you're seeing `NaN` and `undefined` there

Perhaps you could log that out in your example and paste it here so we can compare? Either that or a working example I can clone would be equally helpful!

**Comment by AonghusOh** [comment]
Hi @simonsmith, thanks for the reply!

I've set up a repo for that example here: https://github.com/AonghusOh/cypress-visual-test

**Comment by simonsmith** [comment]
Thanks for creating the example.

I'm not too sure _why_ but I think the cucumber plugin must intefere somehow as when I log out the snapshot result object it's empty.

However it seems if you call `addMatchImageSnapshotPlugin(on)` last in the config it should work

```js
async function setupNodeEvents(on, config) {

  await addCucumberPreprocessorPlugin(on, config);

  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin(config)],
    })
  );

  addMatchImageSnapshotPlugin(on); //  <----- move this here


  return config;
}

```

**Comment by simonsmith** [comment]
I'll close this for now as it seems the workaround fixes this specific use case

**Comment by AonghusOh** [comment]
That workaround works for me @simonsmith - thanks very much! If I gain any more insights into why this might be happening I'll be sure to report back 👍
