### ISSUE TITLE
Snapshot images as a different files

### ISSUE THREAD

**Issue by gagatekns** [simonsmith/cypress-image-snapshot#57]
Snapshot images as a different files.
Hi is the way to get separate images, actual, expected, diff  - instead of one .diff image which contains all of this three images?

So I want to have base image .snap and  diff image as a separate file (only with diffs), and image which was made during test "actual".
Now each of this 3 images(snapshots) are combined into one image

**Comment by simonsmith** [comment]
This plugin is just a wrapper around `jest-image-snapshot`. You could take a look at the options available there:

https://github.com/americanexpress/jest-image-snapshot/tree/main?tab=readme-ov-file#%EF%B8%8F-api

This looks the closest to what you are asking at first glance:

> onlyDiff: (default: false) Either only include the difference between the baseline and the received image in the diff image, or include the 3 images (following the direction set by diffDirection).
