### ISSUE TITLE
allowSizeMismatch is not fixing "Image size different than saved snapshot size" error

### ISSUE THREAD

**Issue by thiagocosenza** [simonsmith/cypress-image-snapshot#59]
Running npx cypress run locally and in CI generates two different sizes in screenshots. So I was expecting this error not to be triggered when setting allowSizeMismatch: true in addMatchImageSnapshotCommand on e2e.js

addMatchImageSnapshotCommand({
    failureThreshold: 0.2,
    comparisonMethod: 'ssim',
    allowSizeMismatch: true
})

**Comment by simonsmith** [comment]
These options come from [jest-image-snapshot](https://github.com/americanexpress/jest-image-snapshot) which this plugin makes use of. I would direct any issues to that repository. But a quick check [of their tests](https://github.com/americanexpress/jest-image-snapshot/blob/da49e578c9a02c50aa841d05ac64e9ffd4b725fd/__tests__/diff-snapshot.spec.js#L358) reveals this:

> `should pass with allowSizeMismatch: true if image passed is a different size but <= failureThreshold pixel`

Could be worth changing what you've set in `failureThreshold` and seeing if that makes a difference
