### ISSUE TITLE
Swipe between base and failed snapshot

### ISSUE THREAD

**Issue by kamiloski88** [simonsmith/cypress-image-snapshot#60]
Is the way to get in report something like in link below (Show diff view and Show overlay view - where I can swipe on image)?

https://github.com/allure-framework/allure2/blob/main/plugins/screen-diff-plugin/README.md

**Comment by simonsmith** [comment]
That is beyond the scope of this plugin. It just generates the diff image. The allure framework in that example also creates a web page and the JS needed to create the onion skin effect

**Comment by gagatekns** [comment]
Do you know how achive this effect? I'm interested too
