### ISSUE TITLE
The acceptable difference between screenshots is not established (failureThreshold)

### ISSUE THREAD

**Issue by NikitaSheff** [simonsmith/cypress-image-snapshot#62]
![image](https://github.com/simonsmith/cypress-image-snapshot/assets/99482593/7699ad8c-5589-443f-ba16-c6106aa72ee4)

Hi!
I've set failureThreshold for 5.5 value
but my tests fail if the difference is 2.0412619972577697%
So I don't want recieve an error if difference is lower than setted value

Thank you

`cy.matchImageSnapshot('GDStartPage',{
            failureThreshold: 6.4,
            blackout: ['.banners'],
        });`

Cypress 13.12

**Comment by maximegheraille** [comment]
Hi @NikitaSheff 

isn't that because 5.5 would be `550%` and therefore just defaults to 0 ?

**Comment by NikitaSheff** [comment]
@maximegheraille No, even 0.4 doesn't work

**Comment by simonsmith** [comment]
`0.01` is 1% so you should use that as your guide.

If you have questions on how the `failureThreshold` works you should consult the [jest-image-snapshot documentation](https://github.com/americanexpress/jest-image-snapshot) as this is doing the actual image comparison
