### ISSUE TITLE
`cy.screenshot()` failed because it requires a DOM element

### ISSUE THREAD

**Issue by pradumangoyal** [simonsmith/cypress-image-snapshot#64]
I am getting an error while running the basic test using the cypress. The issue seems very small, as I can see most of the developers are using it successfully but have spent 2-3 hours already to get it started. 

The test file is:
```javascript
describe('Snapshot Testing', () => {
    context('720p resolution', () => {
        beforeEach(() => {
            cy.viewport(1280, 720);
        });
        it('Create a reference image',{tags: '1'} ,() => {
            cy.visit("a14cf4f0-4365-4b47-a1d9-c2ebb1c0e26c.html");
            cy.get('body').matchImageSnapshot("a14cf4f0-4365-4b47-a1d9-c2ebb1c0e26c");
        });
    });
});
```

While running getting this error
<img width="695" alt="Screenshot 2024-07-10 at 12 53 16 PM" src="https://github.com/simonsmith/cypress-image-snapshot/assets/34851451/1254169e-c1b3-49d8-a02d-3d1177c37513">

**Comment by simonsmith** [comment]
Does your test have an actual `body` element?

**Comment by kamiloski88** [comment]
Show your html, maybe you do not have body
