### ISSUE TITLE
How to catch that there was a diff if failOnSnapshotDiff=false

### ISSUE THREAD

**Issue by kamiloski88** [simonsmith/cypress-image-snapshot#65]
Hi, I can't find how to catch that there was a diff if failOnSnapshotDiff=false.
My case is that I don't want to fail and stop test when diff will occurs, but at the end I want to put this test with diff image into status Broken in my allure report

**Comment by pradumangoyal** [comment]
@kamiloski88 If you are running into this error, I am assuming you must be able to run a simple test using `matchImageSnapshot`. If yes, could you help me with: https://github.com/simonsmith/cypress-image-snapshot/issues/64

**Comment by simonsmith** [comment]
Test suites won't stop when an image snapshot fails, it will just fail that particular test.

The whole point of visual snapshots _is_ to fail the test if there is a mismatch. You should keep `failOnSnapshotDiff` as `true`

**Comment by kamiloski88** [comment]
I want the test to continue after the snapshot is taken, but I want to know how I can catch that the snapshot was taken. 
I use snapshots to verify data in big forms or tables. But very often our Frontend devs make small improvements on UI, then test fails but not because data was wrong so I want to continue the test but I want to catch that snapshot was taken and base on it i want to set this test status as Broken
